---

app_name: "kafka"
ansible_become: true
kafka_port: "9092"
kafka_controller_port: "9093"
kafka_cloud_container_name: "cloudbox-{{ app_name }}"
kafka_version: "4.2.0"
app_volume_prefix: "cloud"
cluster_id: "5L6g3nShT-eMCtK--X86sw"
app_data_volume_name: "{{ app_volume_prefix }}-{{ app_name }}-data"
app_config_volume_name: "{{ app_volume_prefix }}-{{ app_name }}-config"
#app_user_config_volume_name: "{{ app_volume_prefix }}-{{ app_name }}-user-config"
container_data_path: "/var/lib/kafka/data"
container_config_path: "/mnt/shared/config"
#container_user_config_path: "/bitnami/kafka/config"
kafka_auto_create_topics: false
