---

ansible_become: true

create_fs: true

set_repositories_required_repo:
  yum:
    el7:
      - name:  cld-repository-el7
        description: "cld repository el7"
    el8:
      - name:  cld-repository-el8
        description: "cld repository el8"  
    el9:
      - name:  cld-repository-el9
        description: "cld repository el9"
    el10:
      - name:  cld-repository-el10
        description: "cld repository el10"


allowed_interfaces:
- initialize
- expand
- expand_boot
- get_manage_info
- add_mount_point
...
