---

- name: Configure node_exporter firewall service
  ansible.builtin.template:
    src: node_exporter.xml.j2
    dest: /etc/firewalld/services/node_exporter.xml
    mode: '0644'
  ignore_errors: yes

- name: Reload firewalld
  ansible.builtin.command:
    cmd: "firewall-cmd --reload"
  ignore_errors: yes

- name: Add node_exporter service to firewalld
  ansible.builtin.command:
    cmd: "firewall-cmd --add-service=node_exporter --permanent"
  ignore_errors: yes

- name: Reload firewalld
  ansible.builtin.command:
    cmd: "firewall-cmd --reload"
  ignore_errors: yes