---

- name: Configure node_exporter firewall service
  ansible.builtin.template:
    src: node_exporter.xml.j2
    dest: /etc/firewalld/services/node_exporter.xml
    mode: '0644'
  notify: reload firewalld
  ignore_errors: yes

- name: Reload firewalld if service file was created
  ansible.builtin.service:
    name: firewalld
    state: reloaded

- name: Add node_exporter service to firewalld
  ansible.posix.firewalld:
    service: node_exporter
    permanent: yes
    immediate: yes
    state: enabled
  ignore_errors: yes