---

- name: Gather only minimal facts
  setup:
    gather_subset: min

- name: Ensure dcgm_exporter directory exists
  ansible.builtin.file:
    path: "{{ dcgm_exporter_path }}"
    state: directory
    mode: '0755'
  ignore_errors: yes

- name: Install dcgm exporter
  ansible.builtin.get_url:
    url: "{{ dcgm_exporter_url }}.tar.gz"
    dest: "{{ dcgm_exporter_path }}/{{ dcgm_exporter_name }}.tar.gz"
    mode: "0644"
    headers: "{}"
    validate_certs: true
  ignore_errors: yes

- name: Unpack dcgm_exporter tarball
  ansible.builtin.unarchive:
    src: "{{ dcgm_exporter_path }}/{{ dcgm_exporter_name }}.tar.gz"
    dest: "{{ dcgm_exporter_path }}"
    mode: "0755"
    remote_src: true
  ignore_errors: yes

- name: Get firewall status
  ansible.builtin.service_facts:
  no_log: true
  register: service_firewall_facts

- name: Get SELinux status
  ansible.builtin.command: getenforce
  register: selinux_status
  changed_when: false
  ignore_errors: true

- name: Set SELinux context for node_exporter executable
  community.general.sefcontext:
    target: "{{ dcgm_exporter_path }}/nvidia_gpu_exporter"
    setype: bin_t
    state: present
  register: selinux_fcontext
  when: not selinux_status.failed
  ignore_errors: yes

- name: Apply SELinux context to node_exporter executable
  ansible.builtin.command:
    cmd: "restorecon -v {{ dcgm_exporter_path }}/nvidia_gpu_exporter"
  when: selinux_fcontext.changed
  changed_when: false
  ignore_errors: yes

- block:
    - include_tasks: configure-firewalld.yml
  when:
    - service_firewall_facts.ansible_facts.services['firewalld.service'] is defined
    - service_firewall_facts.ansible_facts.services['firewalld.service']['status'] != 'not-found'

- block:
    - include_tasks: configure-ufw.yml
  when:
    - service_firewall_facts.ansible_facts.services['ufw.service'] is defined
    - service_firewall_facts.ansible_facts.services['ufw.service']['status'] != 'not-found'

- name: Configure dcgm_exporter systemd service
  ansible.builtin.template:
    src: dcgm_exporter.service.j2
    dest: /etc/systemd/system/dcgm_exporter.service
    mode: '0644'
  notify:
    - reload systemd
    - start dcgm_exporter
  ignore_errors: yes

- name: Enable dcgm_exporter service
  ansible.builtin.systemd:
    name: dcgm_exporter
    enabled: yes
    state: started
  ignore_errors: yes

