---

- name: Configure dcgm_exporter firewall service
  ansible.builtin.template:
    src: dcgm_exporter.xml.j2
    dest: /etc/firewalld/services/dcgm_exporter.xml
    mode: '0644'
  notify: reload firewalld
  ignore_errors: yes

- name: Reload firewalld if service file was created
  ansible.builtin.service:
    name: firewalld
    state: reloaded

- name: Add dcgm_exporter service to firewalld
  ansible.posix.firewalld:
    service: dcgm_exporter
    permanent: yes
    immediate: yes
    state: enabled
  ignore_errors: yes