---

- name: Configure dcgm_exporter firewall service
  ansible.builtin.template:
    src: dcgm_exporter.xml.j2
    dest: /etc/firewalld/services/dcgm_exporter.xml
    mode: '0644'
  ignore_errors: yes

- name: Reload firewalld
  ansible.builtin.command:
    cmd: "firewall-cmd --reload"
  ignore_errors: yes

- name: Add dcgm_exporter service to firewalld
  ansible.builtin.command:
    cmd: "firewall-cmd --add-service=dcgm_exporter --permanent"
  ignore_errors: yes

- name: Reload firewalld
  ansible.builtin.command:
    cmd: "firewall-cmd --reload"
  ignore_errors: yes