---

nexus_hostname: "{{ nexus_url | urlsplit('hostname') }}"
ansible_become: true
ca_url: "{{ nexus_url }}/repository/products-raw/CA-chain.crt"


set_repositories_repo_keys:
  apt:
    - name: cld-repository
      key_url: "{{ nexus_url }}/repository/products-raw/products-apt.public.gpg.key"
  yum:
    - name:  cld-repository
      key_url: "{{ nexus_url }}/repository/products-raw/products-apt.public.gpg.key"


set_repositories_required_repo:
  apt:
    default:
      - name: cld-repository
        repo_string: "deb {{ nexus_url }}/repository/products-apt/ focal main"
    debian-12:
      - name: cld-repository-debian-12
        repo_string: "deb {{ nexus_url }}/repository/products-apt-debian-12/ bookworm main"
    debian-13:
      - name: cld-repository-debian-13
        repo_string: "deb {{ nexus_url }}/repository/products-apt-debian-13/ trixie main"
    ubuntu-22:
      - name: cld-repository-ubuntu-22
        repo_string: "deb {{ nexus_url }}/repository/products-apt-ubuntu-22/ jammy main"
    ubuntu-24:
      - name: cld-repository-ubuntu-24
        repo_string: "deb {{ nexus_url }}/repository/products-apt-ubuntu-24/ noble main"
    alse-1-8:
      - name: cld-repository-alse-1-8
        repo_string: "deb {{ nexus_url }}/repository/products-apt-alse-1-8/ main main"    

###
# Feature exclusive repos APT
###
#   debian-11:
#     - name: cld-repository-debian-11
#       repo_string: "deb {{ nexus_url }}/repository/products-apt-debian-11/ bullseye main"
#   ubuntu20:
#     - name: cld-repository-ubuntu20
#       repo_string: "deb {{ nexus_url }}/repository/products-apt-ubuntu-20/ focal main"
#   astra-1-7:
#     - name: cld-repository-alse-1-7
#       repo_string: "deb {{ nexus_url }}/repository/products-apt-alse-1-7/ {{ ansible_distribution_version }} main"
###

  yum:
    el7:
      - name:  cld-repository-el7
        repo_string: "{{ nexus_url }}/repository/products-yum/el7/"
        description: "cld repository el7"
    el8:
      - name:  cld-repository-el8
        repo_string: "{{ nexus_url }}/repository/products-yum/el8/"
        description: "cld repository el8"
    el9:
      - name:  cld-repository-el9
        repo_string: "{{ nexus_url }}/repository/products-yum/el9/"
        description: "cld repository el9"
    el10:
      - name:  cld-repository-el10
        repo_string: "{{ nexus_url }}/repository/products-yum/el10/"
        description: "cld repository el10"



set_ca_trust_restart_services: []
set_repositories_apt_proxy: []

...

