---

- name: Start a postgres container with {{ kafka_port }} port exposed
  raw: >
    docker run -d --restart=always --name {{ kafka_cloud_container_name }} \
    -e KAFKA_CFG_ZOOKEEPER_CONNECT="" \
    -e KAFKA_CFG_LISTENERS="CLIENT://:{{ kafka_port }},CONTROLLER://:{{ kafka_controller_port }}" \
    -e KAFKA_CFG_ADVERTISED_LISTENERS="CLIENT://{{ machine['default_v4_address'] }}:{{ kafka_port }}" \
    -e KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP="CLIENT:SASL_PLAINTEXT,CONTROLLER:PLAINTEXT" \
    -e KAFKA_CLIENT_USERS="{{ kafka_user }}" \
    -e KAFKA_CLIENT_PASSWORDS="{{ kafka_password }}" \
    -e KAFKA_CFG_SASL_ENABLED_MECHANISMS="PLAIN" \
    -e KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL="PLAIN" \
    -e KAFKA_INTER_BROKER_LISTENER_NAME="CLIENT" \
    -e KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE="{{ kafka_auto_create_topics }}" \
    -e ALLOW_PLAINTEXT_LISTENER="yes" \
    -e BITNAMI_DEBUG=true \
    -p {{ kafka_port }}:{{ kafka_port }} \
    -v {{ app_data_volume_name }}:{{ container_data_path }} 
    -v {{ app_config_volume_name }}:{{ container_config_path }}
    -v {{ app_user_config_volume_name }}:{{ container_user_config_path }}
    {{ nexus_docker_url }}/bitnami/kafka:{{ kafka_version }}

- set_stats:
    data:
      connection_url: "{{ 'http://' + machine['default_v4_address'] + ':' + kafka_port }}"
      kafka_version: "{{ kafka_version }}"

